[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
